const SERVICE='7d9b0001-6d8f-4f5a-9a42-4a2b1aee1000',COMMAND='7d9b0002-6d8f-4f5a-9a42-4a2b1aee1000',RESPONSE='7d9b0003-6d8f-4f5a-9a42-4a2b1aee1000';
let commandChar,responseChar,device;const encoder=new TextEncoder(),decoder=new TextDecoder(),$=id=>document.getElementById(id);
function show(message){$('status').textContent=message}
function navigate(name){document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.dataset.view===name));document.querySelectorAll('nav [data-go]').forEach(button=>button.classList.toggle('active',button.dataset.go===name));history.replaceState(null,'',name==='home'?'#':'#'+name);window.scrollTo(0,0)}
document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>navigate(button.dataset.go));$('homeButton').onclick=()=>navigate('home');navigate(location.hash.slice(1)||'home');
async function connect(){try{show('Choose SG-SoundPlayer…');device=await navigator.bluetooth.requestDevice({filters:[{services:[SERVICE]}]});device.addEventListener('gattserverdisconnected',()=>show('Disconnected — tap Connect'));const server=await device.gatt.connect(),service=await server.getPrimaryService(SERVICE);commandChar=await service.getCharacteristic(COMMAND);responseChar=await service.getCharacteristic(RESPONSE);show('Connected to '+device.name);const state=await send({cmd:'status'});$('volume').value=state.volume??50;$('volumeValue').value=`${state.volume??50}%`;$('pir').checked=!!state.pir;if(state.ip)$('wifiResult').textContent=`Wi-Fi connected: ${state.ip}`}catch(error){show(error.message)}}
async function readResponse(){return JSON.parse(decoder.decode(await responseChar.readValue()))}
async function send(data){if(!commandChar||!device?.gatt.connected)throw new Error('Tap Connect first');await commandChar.writeValueWithResponse(encoder.encode(JSON.stringify(data)));for(let count=0;count<90;count++){await new Promise(resolve=>setTimeout(resolve,500));const reply=await readResponse();if(reply.status!=='working'&&reply.status!=='connecting'){if(!reply.ok)throw new Error(reply.message||'Command failed');return reply}}throw new Error('The Pi did not respond in time')}
$('connect').onclick=connect;
document.querySelectorAll('[data-sound]').forEach(button=>button.onclick=async()=>{try{await send({cmd:'play',sound:Number(button.dataset.sound)});show(`Playing ${button.textContent}`)}catch(error){show(error.message)}});
$('volume').onchange=async event=>{try{const reply=await send({cmd:'volume',value:Number(event.target.value)});$('volumeValue').value=`${reply.volume}%`}catch(error){show(error.message)}};
$('pir').onchange=async event=>{try{await send({cmd:'pir',enabled:event.target.checked})}catch(error){show(error.message)}};
$('scan').onclick=async()=>{try{$('wifiResult').textContent='Scanning…';const reply=await send({cmd:'scan_wifi'});$('ssid').innerHTML='<option value="">Select a network</option>';reply.networks.forEach(network=>{const option=document.createElement('option');option.value=network.ssid;option.textContent=`${network.ssid} — ${network.signal}%${network.secure?' 🔒':''}`;$('ssid').append(option)});$('wifiResult').textContent=`Found ${reply.networks.length} networks`}catch(error){$('wifiResult').textContent=error.message}};
$('join').onclick=async()=>{const ssid=$('ssid').value;if(!ssid){$('wifiResult').textContent='Select a network first';return}try{$('wifiResult').textContent='Connecting…';const reply=await send({cmd:'connect_wifi',ssid,password:$('password').value});$('wifiResult').textContent=`Connected. Pi address: ${reply.ip||'assigned by router'}`}catch(error){$('wifiResult').textContent=error.message}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
